spring:
  batch:
    initialize-schema: never
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: aszx12qw
    url: jdbc:postgresql://localhost:5432/library
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
  data:
    mongodb:
      port: 27017
      host: localhost
      database: library